# Generated by Django 3.1.5 on 2021-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210201_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('notice', '공지'), ('free', '자유게시판'), ('anon', '익명게시판')], default='free', max_length=10),
        ),
    ]
