# Generated by Django 3.1.5 on 2021-02-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[(None, '-----'), ('notice', '공지'), ('free', '자유게시판'), ('anon', '익명게시판')], default='free', max_length=10),
        ),
    ]
