# Generated by Django 3.1.5 on 2021-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210208_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[(None, '모든 게시판'), ('notice', '공지'), ('free', '자유게시판'), ('anon', '익명게시판')], default='free', max_length=10),
        ),
    ]
