# Generated by Django 3.1.5 on 2021-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210123_2331"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mil_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
