# Generated by Django 3.1.5 on 2021-01-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_mil_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="superhost",
        ),
    ]
