# Generated by Django 3.1.5 on 2021-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blog",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
    ]
