# Generated by Django 3.1.5 on 2021-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_boj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="boj",
            field=models.TextField(blank=True, null=True),
        ),
    ]
