# Generated by Django 3.1.5 on 2021-01-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20210123_2350"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="boj",
            new_name="boj_id",
        ),
    ]
