# Generated by Django 3.1.5 on 2021-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20210123_2351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="github",
        ),
        migrations.AddField(
            model_name="user",
            name="github_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
