# Generated by Django 3.1.5 on 2021-01-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20210123_2354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="boj_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
