# Generated by Django 3.1.5 on 2021-01-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_like_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="like_posts",
        ),
    ]
