# Generated by Django 3.1.5 on 2021-01-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20210124_1127"),
        ("users", "0013_remove_user_like_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="like_posts",
            field=models.ManyToManyField(
                blank=True, related_name="like_users", to="posts.Post"
            ),
        ),
    ]
