# Generated by Django 3.1.5 on 2021-01-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_like_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
