# Generated by Django 3.1.5 on 2021-02-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_posts',
        ),
    ]
