# Generated by Django 3.1.5 on 2021-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_like_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mil_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
