# Generated by Django 3.1.5 on 2021-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210208_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
    ]
