# Generated by Django 3.1.5 on 2021-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="dislike",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="like",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
